using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Akashic_Records_Client : BaseStruct
    {
        public tb_Akashic_Records[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Akashic_Records : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt32 Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public UInt32 Unkown5;
            public Byte Unkown6;
            public UInt16 Unkown7;
            public Byte Unkown8;
            public Byte Unkown9;
            public Byte Unkown10;
            public Byte Unkown11;
            public Byte Unkown12;
            public String Unkown13 = "";
            public String Unkown14 = "";
            public String Unkown15 = "";
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public String Unkown19 = "";
            public UInt16 Unkown20;
            public Byte Unkown21;
            public UInt32 Unkown22;
            public Byte Unkown23;
            public UInt16 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public Byte Unkown28;
            public UInt16 Unkown29;
            public Byte Unkown30;
            public UInt32 Unkown31;
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public UInt32 Unkown34;
            public UInt32 Unkown35;
            public Byte Unkown36;
            public UInt32 Unkown37;
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
