using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Dye_Info_Client : BaseStruct
    {
        public tb_Dye_Info[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Dye_Info : BaseStruct
        {
            public UInt16 Unkown1;
            public UInt32 Unkown2;
            public UInt32 Unkown3;
            public UInt16 Unkown4;
            public UInt16 Unkown5;
            public UInt16 Unkown6;
            public UInt16 Unkown7;
            public UInt16 Unkown8;
            public UInt16 Unkown9;
            public UInt16 Unkown10;
            public UInt16 Unkown11;
            public UInt16 Unkown12;
            public UInt16 Unkown13;
            public UInt32 Unkown14;
            public Byte Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public UInt16 Unkown19;
            public UInt16 Unkown20;
            public UInt16 Unkown21;
            public UInt16 Unkown22;
            public UInt16 Unkown23;
            public UInt16 Unkown24;
            public UInt16 Unkown25;
            public UInt16 Unkown26;
            public UInt16 Unkown27;
            public UInt16 Unkown28;
            public UInt16 Unkown29;
            public UInt16 Unkown30;
            public UInt16 Unkown31;
            public UInt16 Unkown32;
            public UInt16 Unkown33;
            public UInt16 Unkown34;
            public UInt16 Unkown35;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
