using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_DailyMaze_Portal_Client : BaseStruct
    {
        public tb_DailyMaze_Portal[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_DailyMaze_Portal : BaseStruct
        {
            public UInt16 Unkown1;
            public Byte Unkown2;
            public UInt16 Unkown3;
            public UInt16 Unkown4;
            public UInt16 Unkown5;
            public UInt16 Unkown6;
            public UInt16 Unkown7;
            public UInt16 Unkown8;
            public UInt16 Unkown9;
            public UInt16 Unkown10;
            public UInt16 Unkown11;
            public UInt16 Unkown12;
            public UInt16 Unkown13;
            public UInt16 Unkown14;
            public UInt16 Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public UInt16 Unkown19;
            public UInt16 Unkown20;
            public UInt16 Unkown21;
            public UInt16 Unkown22;
            public UInt16 Unkown23;
            public UInt16 Unkown24;
            public UInt16 Unkown25;
            public UInt16 Unkown26;
            public UInt16 Unkown27;
            public UInt16 Unkown28;
            public UInt16 Unkown29;
            public UInt16 Unkown30;
            public UInt16 Unkown31;
            public UInt16 Unkown32;
            public UInt16 Unkown33;
            public UInt16 Unkown34;
            public UInt16 Unkown35;
            public UInt16 Unkown36;
            public UInt16 Unkown37;
            public UInt16 Unkown38;
            public UInt16 Unkown39;
            public UInt16 Unkown40;
            public UInt16 Unkown41;
            public UInt16 Unkown42;
            public UInt16 Unkown43;
            public UInt16 Unkown44;
            public UInt16 Unkown45;
            public UInt16 Unkown46;
            public UInt16 Unkown47;
            public UInt16 Unkown48;
            public String Unkown49 = "";
            public String Unkown50 = "";
            public String Unkown51 = "";
            public String Unkown52 = "";


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
