using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Daily_Mission_Client : BaseStruct
    {
        public tb_Daily_Mission[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Daily_Mission : BaseStruct
        {
            public UInt32 Unkown1;
            public Byte Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public Byte Unkown5;
            public Byte Unkown6;
            public UInt32 Unkown7;
            public Byte Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public Byte Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public Byte Unkown14;
            public Byte Unkown15;
            public String Unkown16 = "";
            public String Unkown17 = "";
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public Byte Unkown22;
            public Byte Unkown23;
            public Byte Unkown24;
            public Byte Unkown25;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
