using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Item_Client : BaseStruct
    {
        public tb_Item[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Item : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt32 Unkown2;
            public Byte Unkown3;
            public Byte Unkown4;
            public UInt16 Unkown5;
            public UInt32 Unkown6;
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt16 Unkown10;
            public Byte Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt16 Unkown15;
            public Byte Unkown16;
            public Byte Unkown17;
            public Byte Unkown18;
            public Byte Unkown19;
            public UInt32 Unkown20;
            public String Unkown21 = "";
            public Byte Unkown22;
            public Byte Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public UInt32 Unkown28;
            public UInt32 Unkown29;
            public Byte Unkown30;
            public Byte Unkown31;
            public Byte Unkown32;
            public Byte Unkown33;
            public Byte Unkown34;
            public UInt32 Unkown35;
            public UInt32 Unkown36;
            public UInt32 Unkown37;
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public Int32 Unkown40;
            public Int32 Unkown41;
            public Int32 Unkown42;
            public Int32 Unkown43;
            public Int32 Unkown44;
            public UInt32 Unkown45;
            public UInt32 Unkown46;
            public UInt32 Unkown47;
            public UInt16 Unkown48;
            public UInt32 Unkown49;
            public UInt32 Unkown50;
            public UInt32 Unkown51;
            public UInt16 Unkown52;
            public UInt32 Unkown53;
            public UInt16 Unkown54;
            public UInt32 Unkown55;
            public Byte Unkown56;
            public UInt16 Unkown57;
            public UInt32 Unkown58;
            public UInt16 Unkown59;
            public Byte Unkown60;
            public Byte Unkown61;
            public UInt32 Unkown62;
            public Byte Unkown63;
            public UInt32 Unkown64;
            public Byte Unkown65;
            public Byte Unkown66;
            public UInt32 Unkown67;
            public UInt32 Unkown68;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
