using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Item_Package_Client : BaseStruct
    {
        public tb_Item_Package[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Item_Package : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt32 Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public UInt32 Unkown5;
            public UInt32 Unkown6;
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public Byte Unkown20;
            public Byte Unkown21;
            public Byte Unkown22;
            public Byte Unkown23;
            public Byte Unkown24;
            public Byte Unkown25;
            public Byte Unkown26;
            public Byte Unkown27;
            public Byte Unkown28;
            public Byte Unkown29;
            public Byte Unkown30;
            public Byte Unkown31;
            public Byte Unkown32;
            public Byte Unkown33;
            public Byte Unkown34;
            public UInt32 Unkown35;
            public UInt32 Unkown36;
            public UInt32 Unkown37;
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;
            public UInt32 Unkown41;
            public UInt32 Unkown42;
            public UInt32 Unkown43;
            public UInt32 Unkown44;
            public UInt32 Unkown45;
            public UInt32 Unkown46;
            public UInt32 Unkown47;
            public UInt32 Unkown48;
            public UInt32 Unkown49;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
