using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Item_RandomBox_Client : BaseStruct
    {
        public tb_Item_RandomBox[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Item_RandomBox : BaseStruct
        {
            public UInt32 Unkown1;
            public Byte Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public UInt16 Unkown5;
            public UInt16 Unkown6;
            public UInt16 Unkown7;
            public UInt16 Unkown8;
            public UInt16 Unkown9;
            public UInt16 Unkown10;
            public UInt16 Unkown11;
            public UInt16 Unkown12;
            public UInt16 Unkown13;
            public UInt16 Unkown14;
            public UInt16 Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public UInt16 Unkown19;
            public UInt16 Unkown20;
            public UInt16 Unkown21;
            public UInt16 Unkown22;
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public UInt32 Unkown28;
            public UInt32 Unkown29;
            public UInt32 Unkown30;
            public UInt32 Unkown31;
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public UInt32 Unkown34;
            public UInt32 Unkown35;
            public UInt32 Unkown36;
            public UInt32 Unkown37;
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;
            public UInt32 Unkown41;
            public UInt32 Unkown42;
            public UInt32 Unkown43;
            public UInt32 Unkown44;
            public UInt32 Unkown45;
            public UInt32 Unkown46;
            public UInt32 Unkown47;
            public UInt32 Unkown48;
            public UInt32 Unkown49;
            public UInt32 Unkown50;
            public UInt32 Unkown51;
            public UInt32 Unkown52;
            public UInt32 Unkown53;
            public UInt32 Unkown54;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
