using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Myroom_Furniture_Client : BaseStruct
    {
        public tb_Myroom_Furniture[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Myroom_Furniture : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt32 Unkown2;
            public String Unkown3 = "";
            public UInt32 Unkown4;
            public UInt32 Unkown5;
            public UInt32 Unkown6;
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public String Unkown19 = "";
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public String Unkown22 = "";
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public String Unkown25 = "";
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public String Unkown28 = "";
            public UInt32 Unkown29;
            public String Unkown30 = "";
            public String Unkown31 = "";
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public UInt32 Unkown34;
            public String Unkown35 = "";
            public String Unkown36 = "";
            public String Unkown37 = "";
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public String Unkown40 = "";
            public UInt32 Unkown41;
            public String Unkown42 = "";
            public String Unkown43 = "";
            public String Unkown44 = "";
            public String Unkown45 = "";
            public String Unkown46 = "";
            public String Unkown47 = "";
            public String Unkown48 = "";
            public String Unkown49 = "";
            public String Unkown50 = "";
            public String Unkown51 = "";
            public String Unkown52 = "";
            public String Unkown53 = "";
            public String Unkown54 = "";
            public String Unkown55 = "";
            public String Unkown56 = "";
            public String Unkown57 = "";
            public String Unkown58 = "";
            public String Unkown59 = "";
            public String Unkown60 = "";
            public String Unkown61 = "";
            public String Unkown62 = "";
            public String Unkown63 = "";
            public String Unkown64 = "";
            public String Unkown65 = "";
            public String Unkown66 = "";
            public String Unkown67 = "";
            public String Unkown68 = "";
            public String Unkown69 = "";
            public String Unkown70 = "";


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
