using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Monster_Client : BaseStruct
    {
        public tb_Monster[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Monster : BaseStruct
        {
            public UInt32 Unkown1;
            public String Unkown2 = "";
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public String Unkown5 = "";
            public String Unkown6 = "";
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public Byte Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public Byte Unkown19;
            public UInt32 Unkown20;
            public Byte Unkown21;
            public Byte Unkown22;
            public Byte Unkown23;
            public Byte Unkown24;
            public Byte Unkown25;
            public Byte Unkown26;
            public Byte Unkown27;
            public String Unkown28 = "";
            public String Unkown29 = "";
            public Byte Unkown30;
            public Byte Unkown31;
            public Byte Unkown32;
            public UInt32 Unkown33;
            public Byte Unkown34;
            public Byte Unkown35;
            public Byte Unkown36;
            public Byte Unkown37;
            public Byte Unkown38;
            public Byte Unkown39;
            public UInt16 Unkown40;
            public UInt16 Unkown41;
            public UInt16 Unkown42;
            public UInt16 Unkown43;
            public Byte Unkown44;
            public UInt32 Unkown45;
            public UInt16 Unkown46;
            public Byte Unkown47;
            public Byte Unkown48;
            public String Unkown49 = "";
            public Byte Unkown50;
            public Byte Unkown51;
            public UInt32 Unkown52;
            public String Unkown53 = "";
            public String Unkown54 = "";
            public Byte Unkown55;
            public Int16 Unkown56;
            public Byte Unkown57;
            public Byte Unkown58;
            public Byte Unkown59;
            public Int16 Unkown60;
            public String Unkown61 = "";
            public String Unkown62 = "";
            public String Unkown63 = "";
            public Byte Unkown64;
            public Byte Unkown65;
            public Byte Unkown66;
            public String Unkown67 = "";
            public String Unkown68 = "";
            public String Unkown69 = "";
            public UInt32 Unkown70;
            public UInt32 Unkown71;
            public UInt32 Unkown72;
            public Byte Unkown73;
            public Byte Unkown74;
            public Byte Unkown75;
            public UInt32 Unkown76;
            public UInt32 Unkown77;
            public UInt32 Unkown78;
            public Byte Unkown79;
            public Byte Unkown80;
            public Byte Unkown81;
            public String Unkown82 = "";
            public String Unkown83 = "";
            public String Unkown84 = "";
            public Int16 Unkown85;
            public Int16 Unkown86;
            public UInt32 Unkown87;
            public UInt32 Unkown88;
            public UInt32 Unkown89;
            public UInt32 Unkown90;
            public UInt32 Unkown91;
            public UInt32 Unkown92;
            public UInt32 Unkown93;
            public UInt32 Unkown94;
            public UInt32 Unkown95;
            public UInt32 Unkown96;
            public UInt32 Unkown97;
            public UInt32 Unkown98;
            public Single Unkown99;
            public UInt32 Unkown100;
            public Byte Unkown101;
            public UInt16 Unkown102;
            public UInt16 Unkown103;
            public Byte Unkown104;
            public Byte Unkown105;
            public String Unkown106 = "";
            public UInt16 Unkown107;
            public UInt16 Unkown108;
            public Single Unkown109;
            public Int16 Unkown110;
            public Byte Unkown111;
            public UInt32 Unkown112;
            public UInt16 Unkown113;
            public UInt16 Unkown114;
            public Byte Unkown115;
            public Int32 Unkown116;
            public Int32 Unkown117;
            public Int32 Unkown118;
            public Int32 Unkown119;
            public Int32 Unkown120;
            public Int32 Unkown121;
            public Int32 Unkown122;
            public Int32 Unkown123;
            public Int32 Unkown124;
            public Int32 Unkown125;
            public Int32 Unkown126;
            public Int32 Unkown127;
            public Int32 Unkown128;
            public Int32 Unkown129;
            public Int32 Unkown130;
            public Int32 Unkown131;
            public Int32 Unkown132;
            public Int32 Unkown133;
            public Int32 Unkown134;
            public Int32 Unkown135;
            public Int32 Unkown136;
            public Int32 Unkown137;
            public Int32 Unkown138;
            public Int32 Unkown139;
            public Int32 Unkown140;
            public Int32 Unkown141;
            public Int32 Unkown142;
            public Int32 Unkown143;
            public Int32 Unkown144;
            public Int32 Unkown145;
            public Int32 Unkown146;
            public Int32 Unkown147;
            public Int32 Unkown148;
            public Int32 Unkown149;
            public String Unkown150 = "";
            public String Unkown151 = "";
            public String Unkown152 = "";
            public String Unkown153 = "";
            public UInt32 Unkown154;
            public Byte Unkown155;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
