using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Mode_District6_Client : BaseStruct
    {
        public tb_Mode_District6[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Mode_District6 : BaseStruct
        {
            public Byte Unkown1;
            public UInt16 Unkown2;
            public UInt32 Unkown3;
            public UInt16 Unkown4;
            public UInt32 Unkown5;
            public UInt16 Unkown6;
            public UInt32 Unkown7;
            public UInt16 Unkown8;
            public UInt32 Unkown9;
            public UInt16 Unkown10;
            public Byte Unkown11;
            public String Unkown12 = "";
            public String Unkown13 = "";
            public String Unkown14 = "";
            public UInt16 Unkown15;
            public Byte Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public UInt32 Unkown22;
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt16 Unkown27;
            public UInt16 Unkown28;
            public UInt16 Unkown29;
            public UInt16 Unkown30;
            public UInt16 Unkown31;
            public UInt16 Unkown32;
            public UInt16 Unkown33;
            public UInt16 Unkown34;
            public UInt16 Unkown35;
            public UInt16 Unkown36;
            public UInt16 Unkown37;
            public UInt16 Unkown38;
            public UInt16 Unkown39;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
