using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Quest_Condition_Client : BaseStruct
    {
        public tb_Quest_Condition[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Quest_Condition : BaseStruct
        {
            public UInt32 Unkown1;
            public Byte Unkown2;
            public UInt32 Unkown3;
            public Byte Unkown4;
            public UInt32 Unkown5;
            public UInt32 Unkown6;
            public Byte Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public UInt32 Unkown22;
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public UInt32 Unkown28;
            public UInt32 Unkown29;
            public UInt32 Unkown30;
            public UInt32 Unkown31;
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public UInt32 Unkown34;
            public UInt32 Unkown35;
            public UInt32 Unkown36;
            public UInt32 Unkown37;
            public Byte Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;
            public Byte Unkown41;
            public Byte Unkown42;
            public UInt32 Unkown43;
            public UInt32 Unkown44;
            public Byte Unkown45;
            public Byte Unkown46;
            public UInt32 Unkown47;
            public UInt32 Unkown48;
            public UInt32 Unkown49;
            public String Unkown50 = "";


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
