using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Reinforce_Client : BaseStruct
    {
        public tb_Reinforce[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Reinforce : BaseStruct
        {
            public UInt32 Unkown1;
            public Byte Unkown2;
            public UInt16 Unkown3;
            public UInt16 Unkown4;
            public UInt16 Unkown5;
            public UInt32 Unkown6;
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public UInt32 Unkown22;
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public UInt32 Unkown28;
            public UInt32 Unkown29;
            public UInt32 Unkown30;
            public UInt32 Unkown31;
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public UInt32 Unkown34;
            public UInt32 Unkown35;
            public UInt32 Unkown36;
            public UInt32 Unkown37;
            public UInt32 Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;
            public UInt32 Unkown41;
            public UInt32 Unkown42;
            public UInt32 Unkown43;
            public UInt32 Unkown44;
            public UInt32 Unkown45;
            public UInt16 Unkown46;
            public UInt16 Unkown47;
            public UInt16 Unkown48;
            public UInt16 Unkown49;
            public UInt16 Unkown50;
            public UInt16 Unkown51;
            public UInt16 Unkown52;
            public UInt16 Unkown53;
            public UInt16 Unkown54;
            public UInt16 Unkown55;
            public UInt32 Unkown56;
            public UInt32 Unkown57;
            public UInt32 Unkown58;
            public UInt32 Unkown59;
            public UInt32 Unkown60;
            public UInt32 Unkown61;
            public UInt32 Unkown62;
            public UInt32 Unkown63;
            public UInt32 Unkown64;
            public UInt32 Unkown65;
            public UInt16 Unkown66;
            public UInt16 Unkown67;
            public UInt16 Unkown68;
            public UInt16 Unkown69;
            public UInt16 Unkown70;
            public UInt16 Unkown71;
            public UInt16 Unkown72;
            public UInt16 Unkown73;
            public UInt16 Unkown74;
            public UInt16 Unkown75;
            public Single Unkown76;
            public Single Unkown77;
            public Single Unkown78;
            public Single Unkown79;
            public Single Unkown80;
            public Single Unkown81;
            public Single Unkown82;
            public Single Unkown83;
            public Single Unkown84;
            public Single Unkown85;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
