using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Random_Option_Client : BaseStruct
    {
        public tb_Random_Option[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Random_Option : BaseStruct
        {
            public UInt32 Unkown1;
            public Byte Unkown2;
            public Byte Unkown3;
            public Byte Unkown4;
            public UInt16 Unkown5;
            public UInt16 Unkown6;
            public UInt16 Unkown7;
            public UInt16 Unkown8;
            public UInt16 Unkown9;
            public UInt16 Unkown10;
            public UInt16 Unkown11;
            public UInt16 Unkown12;
            public UInt16 Unkown13;
            public UInt16 Unkown14;
            public UInt16 Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public UInt16 Unkown19;
            public UInt16 Unkown20;
            public UInt16 Unkown21;
            public UInt16 Unkown22;
            public UInt16 Unkown23;
            public UInt16 Unkown24;
            public UInt16 Unkown25;
            public UInt16 Unkown26;
            public UInt16 Unkown27;
            public UInt16 Unkown28;
            public UInt16 Unkown29;
            public Int32 Unkown30;
            public Int32 Unkown31;
            public Int32 Unkown32;
            public Int32 Unkown33;
            public Int32 Unkown34;
            public Int32 Unkown35;
            public Int32 Unkown36;
            public Int32 Unkown37;
            public Int32 Unkown38;
            public Int32 Unkown39;
            public Int32 Unkown40;
            public Int32 Unkown41;
            public Int32 Unkown42;
            public Int32 Unkown43;
            public Int32 Unkown44;
            public Int32 Unkown45;
            public Int32 Unkown46;
            public Int32 Unkown47;
            public Int32 Unkown48;
            public Int32 Unkown49;
            public Int32 Unkown50;
            public Int32 Unkown51;
            public Int32 Unkown52;
            public Int32 Unkown53;
            public Int32 Unkown54;
            public Int32 Unkown55;
            public Int32 Unkown56;
            public Int32 Unkown57;
            public Int32 Unkown58;
            public Int32 Unkown59;
            public Int32 Unkown60;
            public Int32 Unkown61;
            public Int32 Unkown62;
            public Int32 Unkown63;
            public Int32 Unkown64;
            public Int32 Unkown65;
            public Int32 Unkown66;
            public Int32 Unkown67;
            public Int32 Unkown68;
            public Int32 Unkown69;
            public Int32 Unkown70;
            public Int32 Unkown71;
            public Int32 Unkown72;
            public Int32 Unkown73;
            public Int32 Unkown74;
            public Int32 Unkown75;
            public Int32 Unkown76;
            public Int32 Unkown77;
            public Int32 Unkown78;
            public Int32 Unkown79;
            public UInt32 Unkown80;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
