using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Random_Get_Client : BaseStruct
    {
        public tb_Random_Get[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Random_Get : BaseStruct
        {
            public UInt16 Unkown1;
            public UInt32 Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public UInt32 Unkown5;
            public UInt32 Unkown6;
            public UInt32 Unkown7;
            public UInt32 Unkown8;
            public UInt32 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public UInt32 Unkown18;
            public UInt32 Unkown19;
            public UInt32 Unkown20;
            public UInt32 Unkown21;
            public UInt32 Unkown22;
            public UInt32 Unkown23;
            public UInt32 Unkown24;
            public UInt32 Unkown25;
            public UInt32 Unkown26;
            public UInt32 Unkown27;
            public UInt32 Unkown28;
            public UInt32 Unkown29;
            public UInt32 Unkown30;
            public UInt32 Unkown31;
            public Byte Unkown32;
            public Byte Unkown33;
            public Byte Unkown34;
            public Byte Unkown35;
            public Byte Unkown36;
            public Byte Unkown37;
            public Byte Unkown38;
            public Byte Unkown39;
            public Byte Unkown40;
            public Byte Unkown41;
            public Byte Unkown42;
            public Byte Unkown43;
            public Byte Unkown44;
            public Byte Unkown45;
            public Byte Unkown46;
            public Byte Unkown47;
            public Byte Unkown48;
            public Byte Unkown49;
            public Byte Unkown50;
            public Byte Unkown51;
            public Byte Unkown52;
            public Byte Unkown53;
            public Byte Unkown54;
            public Byte Unkown55;
            public Byte Unkown56;
            public Byte Unkown57;
            public Byte Unkown58;
            public Byte Unkown59;
            public Byte Unkown60;
            public Byte Unkown61;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
