using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Status_Client : BaseStruct
    {
        public tb_Status[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Status : BaseStruct
        {
            public UInt16 Unkown1;
            public Single Unkown2;
            public Single Unkown3;
            public Single Unkown4;
            public Single Unkown5;
            public Single Unkown6;
            public Single Unkown7;
            public Single Unkown8;
            public Single Unkown9;
            public Single Unkown10;
            public Single Unkown11;
            public Single Unkown12;
            public Single Unkown13;
            public Single Unkown14;
            public Single Unkown15;
            public Single Unkown16;
            public Single Unkown17;
            public Single Unkown18;
            public Single Unkown19;
            public Single Unkown20;
            public Single Unkown21;
            public Single Unkown22;
            public Single Unkown23;
            public Single Unkown24;
            public Single Unkown25;
            public Single Unkown26;
            public Single Unkown27;
            public Single Unkown28;
            public Single Unkown29;
            public Single Unkown30;
            public Single Unkown31;
            public Single Unkown32;
            public Single Unkown33;
            public Single Unkown34;
            public Single Unkown35;
            public Single Unkown36;
            public Byte Unkown37;
            public Byte Unkown38;
            public Byte Unkown39;
            public Byte Unkown40;
            public Byte Unkown41;
            public Byte Unkown42;
            public Byte Unkown43;
            public Byte Unkown44;
            public Byte Unkown45;
            public Byte Unkown46;
            public Byte Unkown47;
            public Byte Unkown48;
            public Single Unkown49;
            public Single Unkown50;
            public Single Unkown51;
            public Single Unkown52;
            public Single Unkown53;
            public Single Unkown54;
            public Single Unkown55;
            public Single Unkown56;
            public Single Unkown57;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
