using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Skill_Client : BaseStruct
    {
        public tb_Skill[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Skill : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt16 Unkown2;
            public UInt32 Unkown3;
            public UInt32 Unkown4;
            public Byte Unkown5;
            public Byte Unkown6;
            public Byte Unkown7;
            public Byte Unkown8;
            public Byte Unkown9;
            public Byte Unkown10;
            public Byte Unkown11;
            public Byte Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt32 Unkown15;
            public UInt32 Unkown16;
            public UInt32 Unkown17;
            public Byte Unkown18;
            public Byte Unkown19;
            public Byte Unkown20;
            public Byte Unkown21;
            public UInt16 Unkown22;
            public Single Unkown23;
            public Single Unkown24;
            public Single Unkown25;
            public Single Unkown26;
            public Single Unkown27;
            public Byte Unkown28;
            public UInt16 Unkown29;
            public Byte Unkown30;
            public Byte Unkown31;
            public Byte Unkown32;
            public UInt32 Unkown33;
            public Byte Unkown34;
            public Byte Unkown35;
            public Byte Unkown36;
            public Byte Unkown37;
            public Byte Unkown38;
            public UInt32 Unkown39;
            public UInt32 Unkown40;
            public UInt32 Unkown41;
            public UInt32 Unkown42;
            public UInt32 Unkown43;
            public UInt32 Unkown44;
            public UInt32 Unkown45;
            public Byte Unkown46;
            public UInt16 Unkown47;
            public UInt16 Unkown48;
            public Byte Unkown49;
            public Byte Unkown50;
            public Byte Unkown51;
            public Byte Unkown52;
            public Byte Unkown53;
            public Byte Unkown54;
            public UInt32 Unkown55;
            public Byte Unkown56;
            public UInt32 Unkown57;
            public UInt32 Unkown58;
            public Byte Unkown59;
            public UInt16 Unkown60;
            public String Unkown61 = "";
            public UInt16 Unkown62;
            public UInt32 Unkown63;
            public Byte Unkown64;
            public String Unkown65 = "";
            public String Unkown66 = "";
            public String Unkown67 = "";
            public String Unkown68 = "";
            public Byte Unkown69;
            public UInt32 Unkown70;
            public UInt16 Unkown71;
            public Byte Unkown72;
            public Byte Unkown73;
            public UInt16 Unkown74;
            public String Unkown75 = "";
            public String Unkown76 = "";
            public String Unkown77 = "";
            public Byte Unkown78;
            public String Unkown79 = "";
            public String Unkown80 = "";
            public Byte Unkown81;
            public Byte Unkown82;
            public Byte Unkown83;
            public Byte Unkown84;
            public Byte Unkown85;
            public Byte Unkown86;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
