using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_soul_metry_Client : BaseStruct
    {
        public tb_soul_metry[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_soul_metry : BaseStruct
        {
            public UInt16 Unkown1;
            public UInt16 Unkown2;
            public UInt16 Unkown3;
            public UInt16 Unkown4;
            public UInt16 Unkown5;
            public UInt16 Unkown6;
            public UInt16 Unkown7;
            public UInt16 Unkown8;
            public UInt16 Unkown9;
            public UInt32 Unkown10;
            public UInt32 Unkown11;
            public UInt32 Unkown12;
            public UInt32 Unkown13;
            public UInt32 Unkown14;
            public UInt16 Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public UInt16 Unkown19;
            public String Unkown20 = "";
            public String Unkown21 = "";
            public String Unkown22 = "";
            public String Unkown23 = "";
            public String Unkown24 = "";
            public UInt16 Unkown25;
            public UInt16 Unkown26;
            public UInt16 Unkown27;
            public UInt16 Unkown28;
            public UInt16 Unkown29;
            public Byte Unkown30;
            public Byte Unkown31;
            public UInt32 Unkown32;
            public UInt32 Unkown33;
            public Byte Unkown34;
            public Byte Unkown35;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
