using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Auto Generated by GreenDamTan
//Not verified it work or not
namespace SWAdmin.TableStruct.Client.JP_1_11_9_1
{
    public class tb_Title_Info_Client : BaseStruct
    {
        public tb_Title_Info[] lsData;
        public SWString md5_ = new SWString();

        public override void beforeRead()
        {
        }

        public override void beforeWrite()
        {
        }

        public override void read(SWReader reader)
        {
        }

        public override void write(SWWriter writer)
        {
        }

        public class tb_Title_Info : BaseStruct
        {
            public UInt32 Unkown1;
            public UInt32 Unkown2;
            public Byte Unkown3;
            public Byte Unkown4;
            public UInt16 Unkown5;
            public Byte Unkown6;
            public UInt32 Unkown7;
            public Byte Unkown8;
            public Byte Unkown9;
            public Byte Unkown10;
            public Byte Unkown11;
            public Byte Unkown12;
            public Byte Unkown13;
            public UInt16 Unkown14;
            public UInt16 Unkown15;
            public UInt16 Unkown16;
            public UInt16 Unkown17;
            public UInt16 Unkown18;
            public Single Unkown19;
            public Single Unkown20;
            public Single Unkown21;
            public Single Unkown22;
            public Single Unkown23;


            public override void beforeRead()
            {
            }

            public override void beforeWrite()
            {
            }

            public override void read(SWReader reader)
            {
            }

            public override void write(SWWriter writer)
            {
            }
        }
    }
}
